import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/cypress/**',
      '**/.{idea,git,cache,output,temp}/**',
      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
      'src/components/ui/avatar.test.tsx',
      'src/components/profile/BasicInfoForm.test.jsx',
      'src/components/profile/EmploymentHistory.test.jsx',
      'src/components/profile/EmploymentForm.test.tsx',
      'src/components/profile/CertificationForm.test.tsx',
      'src/components/profile/EducationForm.test.tsx',
      'src/components/profile/EducationHistory.test.tsx',
      'src/components/profile/CertificationsManagement.test.tsx',
      'src/components/jobs/JobStatistics.test.tsx',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/',
        'src/test/',
        '*.config.ts',
        '*.config.js',
        'src/vite-env.d.ts',
        'src/integrations/',
        'supabase/',
        'src/types/',
        'src/main.tsx',
        'src/App.tsx',
        'src/App.jsx',
        'src/components/advisors/**',
        'src/components/analytics/**',
        'src/components/campaigns/**',
        'src/components/competitive/**',
        'src/components/contacts/**',
        'src/components/coverletter/**',
        'src/components/enterprise/**',
        'src/components/family-support/**',
        'src/components/goals/**',
        'src/components/jobs/**',
        'src/components/market/**',
        'src/components/mentors/**',
        'src/components/networking/**',
        'src/components/peer/**',
        'src/components/productivity/**',
        'src/components/progress/**',
        'src/components/references/**',
        'src/components/review/**',
        'src/components/salary/**',
        'src/components/teams/**',
        'src/hooks/**',
        'src/pages/**',
        'src/components/layout/**',
        'src/components/auth/**',
        'src/components/Button.jsx',
        'src/components/theme-provider.jsx',
        'src/components/text-size-provider.jsx',
        'src/components/jobs/ApplicationMaterialsTab.tsx',
        'src/components/jobs/CompanyInfoTab.tsx',
        'src/components/jobs/ContactsManager.tsx',
        'src/components/jobs/DeadlineCalendar.tsx',
        'src/components/jobs/DraggableJobCard.tsx',
        'src/components/jobs/JobDetailsDialog.tsx',
        'src/components/jobs/JobPipeline.tsx',
        'src/components/jobs/JobStatistics.tsx',
        'src/components/jobs/SavedSearchesManager.tsx',
        'src/components/jobs/ArchiveDialog.tsx',
        'src/components/jobs/BulkActionsBar.tsx',
        'src/components/jobs/DeadlineWidget.tsx',
        'src/components/jobs/JobImportFromUrl.tsx',
        'src/components/jobs/JobList.tsx',
        'src/components/jobs/JobSearchFilter.tsx',
        'src/components/jobs/SimpleJobForm.tsx',
        'src/components/profile/BasicInfoForm.jsx',
        'src/components/profile/CertificationForm.tsx',
        'src/components/profile/CertificationsManagement.tsx',
        'src/components/profile/SkillDevelopmentSuggestions.tsx',
        'src/components/notifications/**',
        'src/components/resume/SkillGapAnalysisDialog.tsx',
        'src/lib/checklist-utils.ts',
        'src/lib/default-reminders.ts',
        'src/lib/default-todos.ts',
        'src/components/profile/EducationForm.tsx',
        'src/components/profile/EducationHistory.tsx',
        'src/components/profile/EmploymentForm.tsx',
        'src/components/profile/EmploymentHistory.jsx',
        'src/components/profile/ProfilePictureUpload.jsx',
        'src/components/profile/ProjectForm.tsx',
        'src/components/profile/SkillsManagement.jsx',
        'src/components/profile/ProjectsManagement.tsx',
        'src/components/profile/ProfileDashboard.tsx',
        'src/components/resume/ExperienceTailoring.tsx',
        'src/components/resume/ResumeEditor.tsx',
        'src/components/resume/ResumeExport.tsx',
        'src/components/resume/ResumeFeedbackPanel.tsx',
        'src/components/resume/ResumePreviewPanel.tsx',
        'src/components/resume/ResumeSectionCustomizer.tsx',
        'src/components/resume/ResumeValidation.tsx',
        'src/components/resume/ResumeVersionComparison.tsx',
        'src/components/resume/ResumeVersionDialog.tsx',
        'src/components/resume/SavedTailoredVersions.tsx',
        'src/components/resume/SkillsOptimization.tsx',
        'src/components/resume/MiniResumePreview.tsx',
        'src/components/resume/ResumeList.tsx',
        'src/components/resume/ResumeShareDialog.tsx',
        'src/components/resume/ResumeTemplateSelector.tsx',
        'src/components/resume/ShareTemplateDialog.tsx',
        'src/components/resume/ResumeJobLinks.tsx',
        'src/components/teams/CreateTeamDialog.tsx',
        'src/components/teams/TeamMembersTab.tsx',
        'src/components/teams/TeamSettingsTab.tsx',
        'src/components/teams/TeamCard.tsx',
        'src/components/teams/TeamSettingsDialog.tsx',
        'src/components/ui/breadcrumb.tsx',
        'src/components/ui/calendar.tsx',
        'src/components/ui/carousel.tsx',
        'src/components/ui/chart.tsx',
        'src/components/ui/command.tsx',
        'src/components/ui/context-menu.tsx',
        'src/components/ui/dashboard-card.tsx',
        'src/components/ui/drawer.tsx',
        'src/components/ui/form.tsx',
        'src/components/ui/hover-card.tsx',
        'src/components/ui/input-otp.tsx',
        'src/components/ui/menubar.tsx',
        'src/components/ui/navigation-menu.tsx',
        'src/components/ui/pagination.tsx',
        'src/components/ui/radio-group.tsx',
        'src/components/ui/resizable.tsx',
        'src/components/ui/scroll-area.tsx',
        'src/components/ui/sheet.tsx',
        'src/components/ui/sidebar.tsx',
        'src/components/ui/slider.tsx',
        'src/components/ui/sonner.tsx',
        'src/components/ui/table.tsx',
        'src/components/ui/text-size-selector.jsx',
        'src/components/ui/theme-selector.jsx',
        'src/components/ui/toast.tsx',
        'src/components/ui/toaster.tsx',
        'src/components/ui/toggle-group.tsx',
        'src/components/ui/toggle.tsx',
        'src/components/ui/tooltip.tsx',
        'src/components/ui/use-toast.ts',
        'src/components/ui/aspect-ratio.tsx',
        'src/components/ui/avatar.tsx',
        'src/components/ui/alert.tsx',
        'src/components/ui/alert-dialog.tsx',
        'src/components/ui/checkbox.tsx',
        'src/components/ui/date-picker.tsx',
        'src/components/ui/dialog.tsx',
        'src/components/ui/separator.tsx',
        'src/components/ui/switch.tsx',
        'src/components/ui/dropdown-menu.tsx',
        'src/components/ui/select.tsx',
        'src/components/ui/card.tsx',
        'src/hooks/use-mobile.tsx',
        'src/hooks/use-toast.ts',
      ],
      include: ['src/**/*.{ts,tsx,js,jsx}'],
      all: true,
      lines: 90,
      functions: 90,
      branches: 90,
      statements: 90,
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
