name: ðŸ› Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve this quickly.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - "P1 - Critical (App down, data loss, security breach)"
        - "P2 - High (Major feature broken, >50% users affected)"
        - "P3 - Medium (Non-critical feature broken, <50% users affected)"
        - "P4 - Low (Minor bug, cosmetic issue)"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      options:
        - "Authentication/Login"
        - "Dashboard"
        - "Job Tracking"
        - "Applications"
        - "Contacts/Networking"
        - "Profile"
        - "Documents"
        - "Analytics/Reports"
        - "Map/Location"
        - "Notifications"
        - "Settings"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari
        - Mobile Chrome
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version / Commit
      description: Version or commit hash if known
      placeholder: e.g., v1.2.3 or abc123

  - type: textarea
    id: logs
    attributes:
      label: Console Logs / Error Messages
      description: Any relevant console errors or logs
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
